version: "3"
services:
  springBootApp:
    image: bobby67/bankapp:1.0
    container_name: docker-casestudy-springboot-app
    environment:
      - POSTGRES_HOST=docker-casestudy-springboot-db
    ports:
      - "8088:8097"
    networks:
      - network
    depends_on:
      - postgresDb
    restart: on-failure
 
  postgresDb:
    image: postgres:13.2
    container_name: docker-casestudy-springboot-db
    ports:
      - "5434:5432"
    networks:
      - network
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Virat2002=
      - POSTGRES_DB=Select
networks:
  network:
volumes:
  volume:

 